version = "1.1.13"

[class]
duolingo = "ï€¤"
gcr-prompter = "ï‚„"
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = "ï™´"
kak = "ï…•"
rapid-photo-downloader = "ïŒ‚"
DEFAULT = "ï™ {class}: {title}"
personal = "ï‘™"
libreoffice-calc = "ï‡ƒ"
"org.telegram.desktop" = "ï‹†"
udiskie = "ï‚ "
dmenu-clipboard = "ï‘¬"
work = "ï‘™"
"(?i)feishu" = "ï‚†"
"(?i)thunar" = "ï¼"
kicad = "ï‚­"
".*transmission.*" = "ï€™"
vncviewer = "ï‰•"
sun-awt-x11-xframepeer = "ïƒ§"
virt-manager = "ï‹’"
element = "ï‚†"
"(?i)kitty" = "ï…•"
molotov = "ï‰¬"
"dmenu-pass generator" = "ï‚„"
neomutt = "ïƒ "
darktable = "ï‚ƒ"
vimiv = "ïŒ‚"
vlc = "ï…„"
scli = "ï„²"
org-pwmt-zathura = "ï‡"
cssh = "ï„ "
wire = "ó°€"
sandboxed-tor-browser = "ïˆ•"
qutepreview = "ï…œ"
Signal = "ï„²"
"(?i)sqlitebrowser" = "îŸ„"
libreoffice-impress = "ï‡„"
taskwarrior-tui = "ï‚®"
whatsapp-desktop = "ïˆ²"
discord = "ï’"
shopping = "ï‘™"
jetbrains-studio = "ï…»"
whatsapp-nativefier-d52542 = "ïˆ²"
org-ksnip-ksnip = "ï¥"
xplr = "ï¼"
"Gimp-2.10" = "ï‡…"
snappergui = "ï‘¨"
telegramdesktop = "ï‹†"
"(?i)firefox" = "<span color='orange'>ï‰© </span>"
mpv = "ï‹"
dmenu-pass = "ï‚„"
zoom = "ï€"
org-qutebrowser-qutebrowser = "ï‘™"
"(?i)darktable.*" = "î¸"
qalculate-gtk = "ï‡¬"
bleachbit = "ï„­"
"(?i)waydroid.*" = "droid"
"(?i)alacritty" = "ï„ "
wireshark-gtk = "ïƒ"
pavucontrol = "ïµ"
spotify = "ï†¼"
"(?i)DBeaver Enterprise" = "ğŸ¦«"
obsidian = "ï…‹"
chromium = "ï‰¨"
gsimplecalc = "ï‡¬"
libreoffice-startcenter = "ï‡‚"
libreoffice-writer = "ï‡‚"
swappy = "ï€¾"
dmenu-emoji = "ï–š"
streamlink-twitch-gui = "ï‡¨"
steam = "ï†¶"
songrec = "ï‡‡"
remote-viewer = "ï„ˆ"
"(?i)QQ.*" = "ï‡–"
"(?i)spotify" = "ï†¼"
burp-startburp = "ïŸ¤"
code-oss = "ï„¡"
fontforge = "ï€±"
krita = "ï€¾"
nm-connection-editor = "ïƒ¨"
paperwork = "ï‡˜"
slack = "ï¯"
plexamp = "ï†¼"
wlfreerdp = "ó°€„"
calibre-gui = "ï€­"
wayvnc = "ó°€„"
nemo = "ï¼"
dmenu-browser = "ï€‚"

[class_active]
"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"
DEFAULT = "*{icon}*"

[initial_class]

[initial_class_active]

[workspaces_name]
2 = "two"
5 = "five"
8 = "eight"
4 = "four"
7 = "seven"
1 = "one"
9 = "nine"
6 = "six"
0 = "zero"
10 = "ten"
3 = "three"

[title_in_class."(?i)alacritty"]
"(?i)neomutt" = "neomutt"
"(?i)aerc" = "mail"
joshuto = "file manager"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"
"(?i)bilibili" = "<span color='pink'>{icon}</span>"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"[Ss]team" = "^(Friends List.*)?$"
aProgram = "^$"
"(?i)TestApp" = ""
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "*{icon}*"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
