version = "1.1.12"

# [format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
# dedup = false
# dedup_inactive_fullscreen = false # dedup more
# window delimiter
# delim = " "
# max_clients = 30 # you should not need this

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
# workspace = "{id}:{delim}{clients}" # {id}, {delim} and {clients} are supported
# workspace_empty = "{id}" # {id}, {delim} and {clients} are supported
# client formatter
# client = "{icon}"
# client_active = "*{icon}*"

# deduplicate client formatter
# client_fullscreen = "[{icon}]"
# client_dup = "{client}{counter_sup}"
# client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
# client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"


[class_active]
DEFAULT = "*{icon}*"
"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"

# [initial_class]
# "DEFAULT" = "ï™ {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

[title."(xterm|(?i)kitty|alacritty)"]
"(?i)neomutt" = "mail"

[title_in_class."(?i)alacritty"]
"(?i)neomutt" = "neomutt"
"(?i)aerc" = "mail"
"joshuto"= "file manager"
# regex captures support is supported
# "emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"
"(?i)bilibili" = "<span color='pink'>{icon}</span>"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"" = "^$" # prevent displaying icon for empty class
"(?i)fcitx" = ".*" # will match all title for fcitx
"(?i)TestApp" = "" # will match all title for TestApp
aProgram = "^$" # will match null title for aProgram
"[Ss]team" = "^(Friends List.*)?$" # will match Steam friends list plus all popups (empty titles)

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[class]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = "ï™ {class}: {title}"
# "(?i)Alacritty" = "term"
# "[Ff]irefox" = "browser"
"(?i)darktable.*" = "î¸"
"(?i)waydroid.*" = "droid"
"(?i)DBeaver Enterprise" = "ğŸ¦«"
"(?i)feishu" = "ï‚†"
#"(?i)telegram.*" = "TG"
"(?i)QQ.*" = "ï‡–"
"(?i)thunar" = "ï¼"
"(?i)firefox" = "<span color='orange'>ï‰© </span>"
"(?i)kitty" = "ï…•"
"(?i)alacritty" = "ï„ "
bleachbit = "ï„­"
burp-startburp = "ïŸ¤"
calibre-gui = "ï€­"
"chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default" = "ï™´"
chromium = "ï‰¨"
"Gimp-2.10" = "ï‡…"
code-oss = "ï„¡"
cssh = "ï„ "
darktable = "ï‚ƒ"
discord = "ï’"
dmenu-clipboard = "ï‘¬"
dmenu-pass = "ï‚„"
duolingo = "ï€¤"
element = "ï‚†"
fontforge = "ï€±"
gcr-prompter = "ï‚„"
gsimplecalc = "ï‡¬"
"jetbrains-studio" = "ï…»"
"kak" = "ï…•"
kicad = "ï‚­"
obsidian = "ï…‹"
"dmenu-emoji" = "ï–š"
"dmenu-browser" = "ï€‚"
"dmenu-pass generator" = "ï‚„"
"qalculate-gtk" = "ï‡¬"
krita = "ï€¾"
libreoffice-calc = "ï‡ƒ"
libreoffice-impress = "ï‡„"
libreoffice-startcenter = "ï‡‚"
libreoffice-writer = "ï‡‚"
molotov = "ï‰¬"
mpv = "ï‹"
neomutt = "ïƒ "
nm-connection-editor = "ïƒ¨"
org-ksnip-ksnip = "ï¥"
org-pwmt-zathura = "ï‡"
org-qutebrowser-qutebrowser = "ï‘™"
"org.telegram.desktop" = "ï‹†"
paperwork = "ï‡˜"
pavucontrol = "ïµ"
personal = "ï‘™"
plexamp = "ï†¼"
qutepreview = "ï…œ"
rapid-photo-downloader = "ïŒ‚"
remote-viewer = "ï„ˆ"
sandboxed-tor-browser = "ïˆ•"
scli = "ï„²"
shopping = "ï‘™"
Signal = "ï„²"
slack = "ï¯"
snappergui = "ï‘¨"
songrec = "ï‡‡"
spotify = "ï†¼"
steam = "ï†¶"
streamlink-twitch-gui = "ï‡¨"
sun-awt-x11-xframepeer = "ïƒ§"
swappy = "ï€¾"
taskwarrior-tui = "ï‚®"
telegramdesktop = "ï‹†"
".*transmission.*" = "ï€™"
udiskie = "ï‚ "
vimiv = "ïŒ‚"
virt-manager = "ï‹’"
vlc = "ï…„"
vncviewer = "ï‰•"
wayvnc = "ó°€„"
whatsapp-desktop = "ïˆ²"
whatsapp-nativefier-d52542 = "ïˆ²"
wire = "ó°€"
wireshark-gtk = "ïƒ"
wlfreerdp = "ó°€„"
work = "ï‘™"
xplr = "ï¼"
nemo = "ï¼"
zoom = "ï€"
